[package]
name = "gbemu2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.18.0"
egui = "0.18.1"
dyn-fmt = "0.3.0"
ux = "0.1.5"
const_format = "0.2.28"
